### ISSUE TITLE
[Bug] ModalRoot -> ModalCard

### ISSUE THREAD

**Issue by SkyGopnik** [VKCOM/VKUI#1971]
"@vkontakte/vkui": "^4.17.0",

```
<ModalRoot activeModal={modal} onClose={() => window.history.back()}>
        <Faq id="faq" />
      </ModalRoot>
```
      
 При вызове onClose, activeModal становится null, от ModalCard прилетает ошибка 
 
 ```
 react-dom.development.js?61bb:67 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Object.viewWidth (webpack-internal:///./node_modules/@vkontakte/vkui/dist/components/ModalCardBase/ModalCardBase.js:37:25)
    at AdaptivityConsumer (webpack-internal:///./node_modules/@vkontakte/vkui/dist/hoc/withAdaptivity.js:22:67)
    at div
    at ModalCard (webpack-internal:///./node_modules/@vkontakte/vkui/dist/components/ModalCard/ModalCard.js:35:20)
    at WithPlatform (webpack-internal:///./node_modules/@vkontakte/vkui/dist/hoc/withPlatform.js:17:70)
    at AdaptivityConsumer (webpack-internal:///./node_modules/@vkontakte/vkui/dist/hoc/withAdaptivity.js:22:67)
    at Faq (webpack-internal:///./src/modals/Faq.tsx:12:9)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:233:75)
    at div
    at div
    at div
    at Touch (webpack-internal:///./node_modules/@vkontakte/vkui/dist/components/Touch/Touch.js:29:22)
```

p.s. происходит единожды, последующее открытие и закрытие модалки не вызывает ошибок.

**Comment by SkyGopnik** [comment]
Возможно связано с тем что модалки передаются в Root и структура приложения выглядит так

```
<ConfigProvider scheme={Scheme.BRIGHT_LIGHT}>
        <AdaptivityProvider>
          <AppRoot>
            <Root
              activeView={view}
              modal={<Modals />}
              popout={popout}
            >
              <LoadingView id="loading" />
              <DonateView id="donate" />
            </Root>
          </AppRoot>
        </AdaptivityProvider>
      </ConfigProvider>
```

Т.к. ваша реализация на SplitLayout не особо понятна, куда её впихивать.

**Comment by SkyGopnik** [comment]
> Мы починим, но ничего страшного на самом деле не происходит, не переживайте, просто таймаутик потерялся.

Да я понимаю, просто лучше же чтобы все чистенько было)

**Comment by andressc** [comment]
Здравствуйте, вопросик про данную проблему. У меня сейчас возникло тоже самое.
Проблема исправлена? 
Или не исправлена и просто ждем?

**Comment by AndrewO88** [comment]
тот же вопрос

**Comment by SevereCloud** [comment]
Привет, фикс ворнинга будет доступен в 4.32.0
